#!/bin/sh
#
# live-kde: kde specific setup for livesys
# SPDX-License-Identifier: GPL-3.0-or-later
#


# set up autologin for user evernight
if $(rpm -q plasma-mobile > /dev/null 2>&1) ; then
  DEFAULT_DESKTOP="plasma-mobile.desktop"
  IS_MOBILE=1
else
  DEFAULT_DESKTOP="plasma.desktop"
  IS_MOBILE=0
fi
if [ -f "/etc/plasmalogin.conf" ]; then
sed -i 's/^#User=.*/User=evernight/' /etc/plasmalogin.conf
sed -i "s/^#Session=.*/Session=${DEFAULT_DESKTOP}/" /etc/plasmalogin.conf
else
cat > /etc/plasmalogin.conf << LGNMGR_EOF
[Autologin]
User=evernight
Session=${DEFAULT_DESKTOP}
LGNMGR_EOF
fi

# Inhibit Plasma Setup
touch /etc/plasma-setup-done

# add liveinst.desktop to favorites menu
mkdir -p /home/evernight/.config/
cat > /home/evernight/.config/kickoffrc << MENU_EOF
[Favorites]
FavoriteURLs=/usr/share/applications/org.mozilla.firefox.desktop,/usr/share/applications/org.kde.dolphin.desktop,/usr/share/applications/systemsettings.desktop,/usr/share/applications/org.kde.konsole.desktop,/usr/share/applications/liveinst.desktop
MENU_EOF

# show liveinst.desktop on desktop and in menu
mkdir -p /home/evernight/.local/share/applications/
cp /usr/share/applications/liveinst.desktop /home/evernight/.local/share/applications/
sed -i 's/NoDisplay=true/NoDisplay=false/' /home/evernight/.local/share/applications/liveinst.desktop
# set executable bit disable KDE security warning
chmod +x /home/evernight/.local/share/applications/liveinst.desktop
mkdir /home/evernight/Desktop
cp -a /home/evernight/.local/share/applications/liveinst.desktop /home/evernight/Desktop/

if [ ${IS_MOBILE} -eq 1 ] ; then
# add liveinst.desktop to mobile desktop
mkdir -p /usr/share/plasma/look-and-feel/org.kde.breeze.mobile/contents/plasmoidsetupscripts/
cat > /usr/share/plasma/look-and-feel/org.kde.breeze.mobile/contents/plasmoidsetupscripts/org.kde.plasma.mobile.homescreen.folio.js << APPLETSRC_EOF
applet.writeConfig("Pages", "[[{\"column\":1,\"row\":1,\"storageId\":\"liveinst.desktop\",\"type\":\"application\"}]]");
applet.reloadConfig();
APPLETSRC_EOF
# Clean up the liveinst.desktop after install
cat > /usr/share/anaconda/post-scripts/80-cleanmobile.ks << CLEANAPPLET_EOF
%post

echo "Cleanup liveinst.desktop from mobile"
rm -f /usr/share/plasma/look-and-feel/org.kde.breeze.mobile/contents/plasmoidsetupscripts/org.kde.plasma.mobile.homescreen.folio.js

%end
CLEANAPPLET_EOF

fi

# make kwin react to org.freedesktop.locale1 changes for Anaconda
# https://pagure.io/fedora-kde/SIG/issue/504
cat > /home/evernight/.config/kwinrc << KWINRC_EOF
[Wayland]
FollowLocale1=true
KWINRC_EOF

# For Plasma 6, set up plasma welcome for the live environment
if [ ! -f /etc/xdg/autostart/org.kde.plasma-welcome.desktop ]; then
cat > /home/evernight/.config/plasma-welcomerc << KDEWELCOME_EOF
[General]
LiveEnvironment=true
LiveInstaller=liveinst
KDEWELCOME_EOF
else
# For Plasma 5 plasma-welcome, disable auto-starting
# Cf. https://bugs.kde.org/show_bug.cgi?id=466282
rm -f /etc/xdg/autostart/org.kde.plasma-welcome.desktop
fi

# Set akonadi backend
mkdir -p /home/evernight/.config/akonadi
cat > /home/evernight/.config/akonadi/akonadiserverrc << AKONADI_EOF
[%General]
Driver=QSQLITE3
AKONADI_EOF

# Disable plasma-discover-notifier
mkdir -p /home/evernight/.config/autostart
cp -a /etc/xdg/autostart/org.kde.discover.notifier.desktop /home/evernight/.config/autostart/
echo 'Hidden=true' >> /home/evernight/.config/autostart/org.kde.discover.notifier.desktop

# Disable baloo
cat > /home/evernight/.config/baloofilerc << BALOO_EOF
[Basic Settings]
Indexing-Enabled=false
BALOO_EOF

# Disable kres-migrator
cat > /home/evernight/.kde/share/config/kres-migratorrc << KRES_EOF
[Migration]
Enabled=false
KRES_EOF

# Disable kwallet migrator
cat > /home/evernight/.config/kwalletrc << KWALLET_EOL
[Migration]
alreadyMigrated=true
KWALLET_EOL

# Disable automount of 'known' devices
# https://bugzilla.redhat.com/show_bug.cgi?id=2073708
cat > /home/evernight/.config/kded_device_automounterrc << AUTOMOUNTER_EOF
[General]
AutomountEnabled=false
AutomountOnLogin=false
AutomountOnPlugin=false
AUTOMOUNTER_EOF

# Don't require authentication for starting the installer
cat > /usr/share/polkit-1/rules.d/37-livesys-kde.rules << FOE
polkit.addRule(function(action, subject) {
    if (!subject.local)
        return undefined;
    if (subject.user !== 'evernight')
        return undefined;
    if (action.id.indexOf('org.fedoraproject.pkexec.liveinst') !== 0)
        return undefined;
    return 'yes';
});
FOE

# Apply Evernight Default Avatar
cp /usr/share/pixmaps/system-logo-white.png /var/lib/AccountsService/icons/evernight

cat > /var/lib/AccountsService/users/evernight << AVATAREOF
[User]
Icon=/var/lib/AccountsService/icons/evernight
SystemAccount=false
AVATAREOF

# Fix avatar permissions.
chmod 600 /var/lib/AccountsService/users/evernight
chown root:root /var/lib/AccountsService/users/evernight

# Remove Recycle Bin and Firefox on Desktop
rm /home/evernight/Desktop/trash:⁄.desktop
rm /home/evernight/Desktop/org.mozilla.firefox.desktop

# sudo-rs fix
cat > /etc/sudoers.d/50-live << SUDOEOF
%wheel    ALL=(ALL) NOPASSWD: ALL
SUDOEOF

